### ISSUE TITLE
Uncaught TypeError: this.isLightDescendant is not a function

### ISSUE THREAD

**Issue by jmcgdz** [PolymerElements/iron-behaviors#41]
This line is throwing it: https://github.com/PolymerElements/iron-behaviors/blob/master/iron-control-state.html#L76

@blasten https://github.com/PolymerElements/iron-behaviors/commit/9ffe111fd4ba139be2cf13fa63d29945d8becfc8

I'm on polymer 1.1.3 right now.

The thing is ```isLightDescendant``` is not available until v1.1.5

@notwaldorf https://github.com/Polymer/polymer/commit/1e9110a6cf57bd8e0a850c1aa4a98cadce5c0cb1

but iron-behaviors seems to say polymer ^1.0.0 is ok?

https://github.com/PolymerElements/iron-behaviors/blob/master/bower.json#L19

**Comment by cdata** [comment]
Looks like this is fixed now (`v1.2.0` is the base requirement). If you are stuck on an earlier version of this element, can you include which version is messed up for you in your description and re-open this issue? Thanks!
