### ISSUE TITLE
controls shouldn't change value when disabled

### ISSUE THREAD

**Issue by michaelpg** [PolymerElements/iron-behaviors#9]
In 0.9/0.8, setting a control with both of the iron-behaviors to `disabled = true` results in the `active` property being set to `false`, which ends up changing the value of the controls which use these behaviors.

paper-radio-button, paper-checkbox, paper-toggle-button all rely on the `active` property to show the state of the control. The `active` property is changed by iron-button-state in `_controlStateChanged` when `disabled` is set to `true`. This happens because iron-control-state has an observer on `disabled` which calls `_changedControlState`.

The result is that if a checked checkbox (radio-button, toggle-button) is disabled, it is also unchecked. I would have to write my own helper function to handle disabled changing:

    function disabledChanged(control) {
      // make sure this is called after _changedContolState
      setTimeout(function() {
        var checked = control.checked;
        control.disabled = true;
        control.checked = checked;
      });
    }

But that shouldn't be necessary. The behavior of native HTML input controls is to retain the input value when the control is disabled.

**Comment by blasten** [comment]
This is fixed now in master.
